apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limit-range
  namespace: kube-system
spec:
  limits:
  - default:
      memory: 100Mi
      cpu: 100m
    defaultRequest:
      memory: 50Mi
      cpu: 50m
    type: Container

---
apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limit-range
  namespace: kubecost
spec:
  limits:
  - default:
      memory: 500Mi
      cpu: 500m
    defaultRequest:
      memory: 50Mi
      cpu: 50m
    type: Container

---
apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limit-range
  namespace: nginx-ingress
spec:
  limits:
  - default:
      memory: 1000Mi
      cpu: 1
    defaultRequest:
      memory: 500Mi
      cpu: 500m
    type: Container